"""The contract every S7 pipeline stage passes along.

Epic intake → assessment → design/DFD → human review gate → user stories →
(build → test → docs → release). Each stage consumes and returns these types,
so a stage can be rewritten or replayed without the ones around it changing.

Two project rules are deliberately encoded as types rather than left to
convention, because both are rules that get forgotten under demo pressure:

- `Provenance` — every artifact must say how it was produced. CLAUDE.md is
  explicit that a staged artifact presented as a live AI result is the one
  failure that loses the room, and that the label has to ship with the artifact
  everywhere it is shown. Making it a required field means it cannot be
  forgotten; a renderer that omits it is a visible bug rather than a silent one.

- `Coverage` — an honest 40-70% AI coverage that is articulated beats a claimed
  100% that does not survive a question. Coverage is therefore recorded per
  task, not asserted once at the end.

The hierarchy is `Epic → Assessment → UserStory → Task`. `UserStory` is the
planning artifact a human reads and signs off; `Task` is the executable unit an
agent is handed, and the unit the downstream lane consumes one at a time.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import StrEnum


class Stream(StrEnum):
    """Delivery streams an epic fans out across.

    Not all of them are AI-addressable, which is the whole point of routing by
    stream — see `Coverage`.
    """

    FRONTEND = "frontend"
    API = "api"
    DATABASE = "database"
    DOCUMENT_INTAKE = "document_intake"
    SYSTEM_OF_RECORD = "system_of_record"
    TEST = "test"


class Coverage(StrEnum):
    """How a task actually gets done. The honest answer, per CLAUDE.md."""

    AGENTIC = "agentic"
    """Runs agentically end to end in this pipeline."""

    AI_ASSISTED_EXTERNAL = "ai_assisted_external"
    """AI drafts it, but another team owns the change and its lead time."""

    MANUAL = "manual"
    """Human work. No AI contribution claimed."""


class Provenance(StrEnum):
    """How an artifact was produced. Required on everything the demo displays."""

    LIVE_AI = "live_ai"
    """Generated by a live model call during this run."""

    REPLAYED_AI = "replayed_ai"
    """Reproduced from a committed replay recording. Genuine AI output, recorded
    earlier — the demo-day default under hard rule 5."""

    STAGED = "staged"
    """Prepared by hand ahead of time because it could not be produced live.
    Permitted only when labelled as staged wherever it is shown."""

    HUMAN = "human"
    """Authored by a person — an epic, or a reviewer's decision."""

    @property
    def needs_label(self) -> bool:
        """True when a renderer must show the provenance badge prominently.

        Staged output is the case the rule exists for.
        """
        return self is Provenance.STAGED


class GateDecision(StrEnum):
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"


@dataclass(frozen=True)
class Epic:
    """A business requirement at epic level — the S7 entry point."""

    id: str
    title: str
    body: str
    source_path: str
    provenance: Provenance = Provenance.HUMAN


@dataclass(frozen=True)
class AssessedTask:
    """One unit of the epic, routed to a stream and honestly labelled."""

    id: str
    summary: str
    stream: Stream
    coverage: Coverage
    estimate_days: float
    rationale: str
    depends_on: tuple[str, ...] = ()
    blocked_by_external: bool = False
    """True when this task waits on a change another team owns — the mainframe
    field addition every other stream then queues behind."""


@dataclass(frozen=True)
class Assessment:
    """The initial AI assessment: the epic fanned out across streams."""

    epic_id: str
    tasks: tuple[AssessedTask, ...]
    integration_note: str
    provenance: Provenance
    generated_at: datetime

    def coverage_breakdown(self) -> dict[Coverage, float]:
        """Share of estimated effort by coverage class.

        Weighted by estimate rather than task count: ten trivial agentic tasks
        beside one large manual one is not 91% AI coverage, and reporting it
        that way is exactly the overclaim this project is trying to avoid.
        """
        total = sum(t.estimate_days for t in self.tasks)
        if total <= 0:
            return {}
        totals: dict[Coverage, float] = {}
        for task in self.tasks:
            totals[task.coverage] = totals.get(task.coverage, 0.0) + task.estimate_days
        return {c: round(d / total, 4) for c, d in totals.items()}


@dataclass(frozen=True)
class DesignArtifact:
    """A generated design output — a DFD or a relationship diagram.

    `source` is diagram source text (Mermaid), not a rendered image, so it
    diffs in review and needs no rendering toolchain in a locked-down sandbox.
    """

    id: str
    kind: str
    title: str
    source: str
    notes: str
    provenance: Provenance


@dataclass(frozen=True)
class ReviewGate:
    """The human review gate. Load-bearing, not decorative.

    Story breakdown must not run until `decision` is APPROVED. The gate records
    who decided and why so the demo can show a rejection changing the outcome
    rather than a rubber stamp.
    """

    epic_id: str
    decision: GateDecision
    reviewer: str | None = None
    decided_at: datetime | None = None
    comment: str = ""

    @property
    def may_proceed(self) -> bool:
        return self.decision is GateDecision.APPROVED


@dataclass(frozen=True)
class AcceptanceCriterion:
    id: str
    text: str


@dataclass(frozen=True)
class Task:
    """The executable unit below a story — what the downstream lane picks up.

    Settled 2026-08-04, after the design review made explicit that the S3-style
    lane consumes *a task at a time*, not a whole story, and that the breakdown
    is driven by technology, by owning team, and by who has access to which
    repository. `UserStory` remains the planning artifact and the thing a human
    reads; `Task` is the thing an agent is handed.

    Two rules from the review are encoded here rather than left to convention:

    - `satisfies` names the acceptance criteria this task delivers. Traceability
      is a field, not a paragraph — a task that satisfies nothing is either
      mis-decomposed or scope nobody asked for, and `UserStory.unsatisfied()`
      makes the gap visible instead of leaving it to be noticed.
    - `coverage` is where the two scopes stitch together. Only `AGENTIC` tasks
      go down the automated lane; the rest follow the normal development cycle
      and are labelled as such. This is the same honesty `Assessment` applies to
      an epic, applied one level down.
    """

    id: str
    story_id: str
    summary: str
    stream: Stream
    coverage: Coverage
    estimate_days: float
    provenance: Provenance
    satisfies: tuple[str, ...] = ()
    """Ids of the `AcceptanceCriterion` entries this task delivers."""
    depends_on: tuple[str, ...] = ()
    owning_team: str | None = None
    """Set when the change is owned outside this pipeline. Names who is waited
    on, so a blocked task reads as a queue rather than as a failure."""

    @property
    def runs_in_downstream_lane(self) -> bool:
        """True when build → test → docs → release may pick this task up.

        Anything else is a change someone makes by hand, and claiming otherwise
        is the overclaim this repo exists to avoid.
        """
        return self.coverage is Coverage.AGENTIC


@dataclass(frozen=True)
class UserStory:
    """The convergence point of the two modes.

    Project mode reaches this shape by way of epic → design → gate. Enhancement
    mode (S3-style) starts here. Everything downstream consumes this and does
    not care which mode produced it.

    A story is not itself executable — it decomposes into `tasks`, and those are
    what the downstream lane consumes. `tasks` defaults to empty because
    decomposition is a later stage than breakdown: a story that has passed the
    gate but not yet been decomposed is a real state, not an incomplete object.
    """

    id: str
    title: str
    narrative: str
    acceptance: tuple[AcceptanceCriterion, ...]
    streams: tuple[Stream, ...]
    estimate_points: int
    provenance: Provenance
    epic_id: str | None = None
    assumptions: tuple[str, ...] = ()
    """Anything resting on an unvalidated SME question. Carried, not buried —
    EPIC-S7-001 §10 lists questions that must not be silently invented."""
    tasks: tuple[Task, ...] = ()

    def unsatisfied(self) -> tuple[str, ...]:
        """Acceptance criterion ids no task claims to deliver.

        Empty is the only good answer once decomposition has run. Reported
        rather than raised: an undecomposed story returns every criterion, which
        is correct and not an error.
        """
        claimed = {ac_id for task in self.tasks for ac_id in task.satisfies}
        return tuple(ac.id for ac in self.acceptance if ac.id not in claimed)

    def coverage_breakdown(self) -> dict[Coverage, float]:
        """Share of this story's estimated effort by coverage class.

        Same effort weighting as `Assessment.coverage_breakdown`, and same
        reason — counting tasks instead of days is how a coverage claim goes
        wrong. Returns `{}` for an undecomposed story: nothing measured, so
        nothing reported.
        """
        total = sum(t.estimate_days for t in self.tasks)
        if total <= 0:
            return {}
        totals: dict[Coverage, float] = {}
        for task in self.tasks:
            totals[task.coverage] = totals.get(task.coverage, 0.0) + task.estimate_days
        return {c: round(d / total, 4) for c, d in totals.items()}


@dataclass
class RunRecord:
    """One pipeline run, for the delivery KPIs S7 is measured on."""

    run_id: str
    epic_id: str
    started_at: datetime
    stages: list[str] = field(default_factory=list)
    finished_at: datetime | None = None

    def stage_done(self, name: str) -> None:
        self.stages.append(name)
